[selector]
type = "file"
source = "some/path/to/folder/"
post_order = "filename"

[poster]
type = "multi"

[[poster.posters]]
type = "telegram"
name = "first"
chat = "@durov"
client = { name = "name" }

[[poster.posters]]
type = "highres"
name = "second"
chat = ["@onetimeusername", -1001408858031]

[poster.posters.client]
api_id = 17349
api_hash = "344583e45741c457fe1862106095a5eb"
bot_token = "1229760154:AAGoQ04f8625xhgj8E0lgFMWScxnjLc4If4"
